### ISSUE TITLE
Création des milestones / issues / tableau kanban

### ISSUE THREAD

**Issue by Sarah-Hans** [Sarah-Hans/CN_JS_Project#2]
- [x] Création des milestones
- [x] Création des issues
- [x] Création du kanban (automatisé)
